apiVersion: v2
name: k8s-images-manager
description: A Helm chart for Kubernetes
version: 0.1.7
appVersion: 0.1.7
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Kubernetes_logo.svg/1280px-Kubernetes_logo.svg.png
