<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 64 64"
    fill="none"
    class="icon w-full h-auto"
    aria-hidden="true"
  >
    <rect
      x="10"
      y="8"
      width="44"
      height="14"
      rx="3"
      fill="#fff"
      stroke="#000"
      stroke-width="3"
    />
    <rect
      x="10"
      y="25"
      width="44"
      height="14"
      rx="3"
      fill="#fff"
      stroke="#000"
      stroke-width="3"
    />
    <rect
      x="10"
      y="42"
      width="44"
      height="14"
      rx="3"
      fill="#fff"
      stroke="#000"
      stroke-width="3"
    />
    <circle
      cx="17"
      cy="15"
      r="2.5"
      fill="#6DBF8A"
      stroke="#000"
      stroke-width="1.5"
    />
    <circle
      cx="24"
      cy="15"
      r="2.5"
      fill="#4EC8D8"
      stroke="#000"
      stroke-width="1.5"
    />
    <circle
      cx="17"
      cy="32"
      r="2.5"
      fill="#6DBF8A"
      stroke="#000"
      stroke-width="1.5"
    />
    <circle
      cx="24"
      cy="32"
      r="2.5"
      fill="#4EC8D8"
      stroke="#000"
      stroke-width="1.5"
    />
    <circle
      cx="17"
      cy="49"
      r="2.5"
      fill="#6DBF8A"
      stroke="#000"
      stroke-width="1.5"
    />
    <circle
      cx="24"
      cy="49"
      r="2.5"
      fill="#4EC8D8"
      stroke="#000"
      stroke-width="1.5"
    />
    <path
      d="M36 13h18M36 30h18M36 47h18"
      stroke="#000"
      stroke-width="2"
      stroke-linecap="round"
    />
  </svg>
</template>
