# https://github.com/goreleaser/example-rust/blob/main/.goreleaser.yaml

version: 2

project_name: k8s-images-manager-agent

# Hooks ran before actually building anything.
# Here we use them to prepare for building.
before:
  hooks:
    - rustup default stable
    - rustup target add x86_64-unknown-linux-musl
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    targets:
      - x86_64-unknown-linux-gnu
      #- aarch64-unknown-linux-gnu
      #- x86_64-apple-darwin
      #- x86_64-pc-windows-gnu
      #- aarch64-apple-darwin

changelog:
  use: github
  format: "{{.SHA}}: {{.Message}} made by (@{{.AuthorUsername}})"
  sort: asc

  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Chores"
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

  filters:
    exclude:
      - "^docs:"
      - "^test:"

# A footer to add to all releases.
release:
  footer: >-

    ---

    Released with ❤️ by unicorns. 🦄

universal_binaries:
  - replace: false

# Enables source archives.
source:
  enabled: true

# SBOMs for the archives.
#sboms:
#  - artifacts: archive
# Sign binaries with cosign.
#signs:
#  - cmd: cosign
#    certificate: "${artifact}.pem"
#    args:
#      - sign-blob
#      - "--output-certificate=${certificate}"
#      - "--output-signature=${signature}"
#      - "${artifact}"
#      - "--yes"
#    artifacts: checksum

dockers_v2:
  - images:
      - "ghcr.io/tchoupinax/k8s-images-manager"
      - "docker.io/tchoupinax/k8s-images-manager"
    tags:
      - "agent-v{{ .Version }}"
    platforms:
      - linux/amd64
      # - linux/arm64
    labels:
      "org.opencontainers.image.description": "Agent"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
#
# Sign the Docker images with cosign as well.
#docker_signs:
#  - cmd: cosign
#    artifacts: manifests
#    args:
#      - "sign"
#      - "${artifact}"
#      - "--yes"
#
# Sets up homebrew-taps.
# PS: this will require a personal access token, as it is cross-repository.
#brews:
#  - repository:
#      owner: goreleaser
#      name: example-homebrew-tap
#      token: "{{ .Env.GH_PAT }}"
#    directory: Formula
#    homepage: https://goreleaser.com
#    description: Example rust release.
#    license: MIT
#    # usually you don't need to set this, we do to prevent conflicts with other
#    # example-* repositories
#    name: example-rust
