FROM rust:1.93 AS builder

WORKDIR /app

RUN apt update && apt install -y pkg-config libssl-dev

COPY . .
RUN cargo build --release

##########################################################################################
##########################################################################################
##########################################################################################
FROM ubuntu

WORKDIR /app

#RUN apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common -y
RUN apt update
RUN apt install -y ca-certificates
RUN apt install -y curl --fix-missing
RUN apt install -y gpg

RUN echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.30/deb/ /" | tee /etc/apt/sources.list.d/cri-o.list
RUN curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg

RUN apt update
RUN apt install -y wget
RUN wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.32.0/crictl-v1.32.0-linux-amd64.tar.gz
RUN tar zxvf crictl-v1.32.0-linux-amd64.tar.gz -C /usr/local/bin
RUN crictl --version

COPY --from=builder /app/target/release/k8s-images-manager-agent /app/k8s-images-manager-agent

CMD ["/bin/sh", "-c", "/app/k8s-images-manager-agent && sleep 300"]
