FROM node:25-alpine AS builder

WORKDIR /app

RUN npm i -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY webapp/package.json webapp/

# hadolint ignore=DL3042
RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
    pnpm install --frozen-lockfile --store-dir /root/.pnpm-store --filter=webapp

COPY webapp webapp

RUN pnpm --filter webapp build

FROM node:25-alpine

RUN addgroup -S -g 1001 k8simagemanager && \
    adduser -S -u 1001 -G k8simagemanager k8simagemanager

WORKDIR /app

COPY --from=builder /app/webapp/.output .output

RUN chown -R k8simagemanager:k8simagemanager /app

USER 1001

CMD ["node", ".output/server/index.mjs"]
