name: Build webapp + docker image

on:
  push:
    tags:
    - v*

permissions:
  contents: read
  packages: write

jobs:
  webapp-build:
    name: "📊 Build webapp"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: "Setup PNPM"
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

    - name: Use Node.js 25
      uses: actions/setup-node@v6
      with:
        node-version: 25
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      working-directory: webapp

    - name: Build Nuxt.js app
      run: pnpm build
      working-directory: webapp

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: frontend-build
        path: webapp/.output
        retention-days: 1
        include-hidden-files: true

  webapp-docker:
    name: "📊 Dockerize webapp"
    runs-on: ubuntu-latest
    needs: webapp-build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Download build artifacts
      uses: actions/download-artifact@v8
      with:
        name: frontend-build
        path: webapp/.output/

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Extract Git tag
      id: git_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push Docker images
      uses: docker/build-push-action@v7
      with:
        file: "webapp/Dockerfile"
        context: "."
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/tchoupinax/k8s-images-manager:webapp-${{ env.TAG }}
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/k8s-images-manager:webapp-${{ env.TAG }}
        labels: "org.opencontainers.image.version=${{ env.TAG }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
